### ISSUE TITLE
Question about ’requirements.txt’ contents

### ISSUE THREAD

**Issue by yonuyeung** [GirinChutia/FasterRCNN-Torchvision-FineTuning#2]
Hello,

I noticed that the `requirements.txt` file in the project contains multiple different versions of the same libraries, which seems unusual. Specifically, there are duplicate entries for libraries like Pillow and opencv-python with different versions.

Here is an example from the `requirements.txt` file:

```plaintext
Pillow==9.3.0
Pillow==10.0.0
opencv_python_headless==4.5.4.60
opencv-python-headless==4.6.0.66
```

I'm curious to understand the reason behind including multiple versions of the same library in the requirements file. Generally, it's recommended to specify one consistent version for each library to avoid potential dependency conflicts and maintain consistency.

Could you please provide some context or clarify why this approach was taken? It would be helpful for users like me to understand the rationale behind it.

Thank you for your attention to this matter, and I look forward to your response.

**Comment by yonuyeung** [comment]
Furthermore, I have found that the versions of opencv-python and opencv-python-headless need to be consistent, otherwise it will result in an error message 'module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline'.

**Comment by GirinChutia** [comment]
Hi @yonuyeung , thanks for pointing it out. Its an oversight from my side. I'll update the _requirements.txt_ file soon.
