### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by eyegotthis** [GirinChutia/FasterRCNN-Torchvision-FineTuning#3]
Hey Girin,

Thanks alot for such an amazing work! Everything works as explained. Is it possible for you to attach a License to this repository? That will be of alot of help :D 

Cheers,
Esas

**Comment by GirinChutia** [comment]
Hi Esas,
The codebase is licensed under the MIT License. I've included the license file in the repository. If it benefits you, kindly give the repo a star.
Cheers!

**Comment by eyegotthis** [comment]
Thank you very much! Starred :)
